version: '3'
services:
  db:
    image: mysql:5.7.24
    restart: always
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d 
  frontend: 
    image: haohan11/ff-nextjs:3.0.1
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_BACKEND_PORT=http://backend:3001
      - NEXT_PUBLIC_BACKEND_PORT_LOCAL=http://localhost:3001
  backend: 
    image: haohan11/ff-nodejs:2.0.0
    ports:
      - '3001:3001'